apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-with-directory
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: directory
  source:
    repoURL: https://github.com/mhdan/argocd-tutorial.git
    path: v03-argocd-applications/directoryOfmanifests
    targetRevision: main
    directory:
      include: '{serviceaccount.yml,service.yml}'
